name: .NET Continuous Deployment

on:
  push:
    tags:
      - '*'

env:
  Build_Configuration: Release
  Cake_File: build.cake
  Build_Target: Default

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
          
    - name: .NET Build and Test
      uses: cake-build/cake-action@v2
      with:
        script-path: ${{ env.Cake_File }}
        target: ${{ env.Build_Target }}
        verbosity: Diagnostic
        arguments: |
          configuration: ${{ env.Build_Configuration }}
    
        