name: RichillCapital.Domain - Continuous Deployment

on:
  push:
    tags:
      - '*'

env:
  PROJECT_PATH: ./RichillCapital.Domain.csproj
  CAKE_FILE_PATH: ./build.cake
  TARGET: Default
  CONFIGURATION: Release

jobs:
  push-nuget:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Determine the Deploy Version
      id: version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
    
    - name: Update Version
      run: |
        sudo apt-get install -y xmlstarlet
        package_version=${{ steps.version.outputs.version }}
        xmlstarlet ed --inplace -u "/Project/PropertyGroup/Version" -v "${package_version}" ${{ env.PROJECT_PATH }}
        
    - name: .NET Build and Tests
      uses: cake-build/cake-action@v2
      with:
        script-path: ${{ env.CAKE_FILE_PATH }}
        target: ${{ env.TARGET }}
        verbosity: Diagnostic
        arguments: |
          configuration: ${{ env.Configuration }}
    
    - name: Push to NuGet Gallery
      run: |
        dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}